// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloudnic.proto

#include "cloudnic.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cloudnic {
PROTOBUF_CONSTEXPR CompressImgReq::CompressImgReq(
    ::_pbi::ConstantInitialized)
  : img_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , img_id_(int64_t{0}){}
struct CompressImgReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompressImgReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompressImgReqDefaultTypeInternal() {}
  union {
    CompressImgReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompressImgReqDefaultTypeInternal _CompressImgReq_default_instance_;
PROTOBUF_CONSTEXPR CompressImgResp::CompressImgResp(
    ::_pbi::ConstantInitialized)
  : img_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , img_id_(int64_t{0}){}
struct CompressImgRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompressImgRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompressImgRespDefaultTypeInternal() {}
  union {
    CompressImgResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompressImgRespDefaultTypeInternal _CompressImgResp_default_instance_;
}  // namespace cloudnic
namespace cloudnic {

// ===================================================================

class CompressImgReq::_Internal {
 public:
  using HasBits = decltype(std::declval<CompressImgReq>()._has_bits_);
  static void set_has_img_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_img(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CompressImgReq::CompressImgReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cloudnic.CompressImgReq)
}
CompressImgReq::CompressImgReq(const CompressImgReq& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  img_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    img_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_img()) {
    img_.Set(from._internal_img(), 
      GetArenaForAllocation());
  }
  img_id_ = from.img_id_;
  // @@protoc_insertion_point(copy_constructor:cloudnic.CompressImgReq)
}

inline void CompressImgReq::SharedCtor() {
img_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  img_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
img_id_ = int64_t{0};
}

CompressImgReq::~CompressImgReq() {
  // @@protoc_insertion_point(destructor:cloudnic.CompressImgReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CompressImgReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  img_.Destroy();
}

void CompressImgReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CompressImgReq::Clear() {
// @@protoc_insertion_point(message_clear_start:cloudnic.CompressImgReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    img_.ClearNonDefaultToEmpty();
  }
  img_id_ = int64_t{0};
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CompressImgReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int64 img_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_img_id(&has_bits);
          img_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes img = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_img();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CompressImgReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloudnic.CompressImgReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional int64 img_id = 1;
  if (_internal_has_img_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_img_id(), target);
  }

  // optional bytes img = 2;
  if (_internal_has_img()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_img(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloudnic.CompressImgReq)
  return target;
}

size_t CompressImgReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cloudnic.CompressImgReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional bytes img = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_img());
    }

    // optional int64 img_id = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_img_id());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CompressImgReq::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CompressImgReq*>(
      &from));
}

void CompressImgReq::MergeFrom(const CompressImgReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cloudnic.CompressImgReq)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_img(from._internal_img());
    }
    if (cached_has_bits & 0x00000002u) {
      img_id_ = from.img_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CompressImgReq::CopyFrom(const CompressImgReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cloudnic.CompressImgReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompressImgReq::IsInitialized() const {
  return true;
}

void CompressImgReq::InternalSwap(CompressImgReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &img_, lhs_arena,
      &other->img_, rhs_arena
  );
  swap(img_id_, other->img_id_);
}

std::string CompressImgReq::GetTypeName() const {
  return "cloudnic.CompressImgReq";
}


// ===================================================================

class CompressImgResp::_Internal {
 public:
  using HasBits = decltype(std::declval<CompressImgResp>()._has_bits_);
  static void set_has_img_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_img(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CompressImgResp::CompressImgResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cloudnic.CompressImgResp)
}
CompressImgResp::CompressImgResp(const CompressImgResp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  img_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    img_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_img()) {
    img_.Set(from._internal_img(), 
      GetArenaForAllocation());
  }
  img_id_ = from.img_id_;
  // @@protoc_insertion_point(copy_constructor:cloudnic.CompressImgResp)
}

inline void CompressImgResp::SharedCtor() {
img_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  img_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
img_id_ = int64_t{0};
}

CompressImgResp::~CompressImgResp() {
  // @@protoc_insertion_point(destructor:cloudnic.CompressImgResp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CompressImgResp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  img_.Destroy();
}

void CompressImgResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CompressImgResp::Clear() {
// @@protoc_insertion_point(message_clear_start:cloudnic.CompressImgResp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    img_.ClearNonDefaultToEmpty();
  }
  img_id_ = int64_t{0};
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CompressImgResp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int64 img_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_img_id(&has_bits);
          img_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes img = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_img();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CompressImgResp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloudnic.CompressImgResp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional int64 img_id = 1;
  if (_internal_has_img_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_img_id(), target);
  }

  // optional bytes img = 2;
  if (_internal_has_img()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_img(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloudnic.CompressImgResp)
  return target;
}

size_t CompressImgResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cloudnic.CompressImgResp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional bytes img = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_img());
    }

    // optional int64 img_id = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_img_id());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CompressImgResp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CompressImgResp*>(
      &from));
}

void CompressImgResp::MergeFrom(const CompressImgResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cloudnic.CompressImgResp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_img(from._internal_img());
    }
    if (cached_has_bits & 0x00000002u) {
      img_id_ = from.img_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CompressImgResp::CopyFrom(const CompressImgResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cloudnic.CompressImgResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompressImgResp::IsInitialized() const {
  return true;
}

void CompressImgResp::InternalSwap(CompressImgResp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &img_, lhs_arena,
      &other->img_, rhs_arena
  );
  swap(img_id_, other->img_id_);
}

std::string CompressImgResp::GetTypeName() const {
  return "cloudnic.CompressImgResp";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace cloudnic
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cloudnic::CompressImgReq*
Arena::CreateMaybeMessage< ::cloudnic::CompressImgReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cloudnic::CompressImgReq >(arena);
}
template<> PROTOBUF_NOINLINE ::cloudnic::CompressImgResp*
Arena::CreateMaybeMessage< ::cloudnic::CompressImgResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cloudnic::CompressImgResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
