// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloudnic.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cloudnic_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cloudnic_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cloudnic_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cloudnic_2eproto {
  static const uint32_t offsets[];
};
namespace cloudnic {
class CompressImgReq;
struct CompressImgReqDefaultTypeInternal;
extern CompressImgReqDefaultTypeInternal _CompressImgReq_default_instance_;
class CompressImgResp;
struct CompressImgRespDefaultTypeInternal;
extern CompressImgRespDefaultTypeInternal _CompressImgResp_default_instance_;
}  // namespace cloudnic
PROTOBUF_NAMESPACE_OPEN
template<> ::cloudnic::CompressImgReq* Arena::CreateMaybeMessage<::cloudnic::CompressImgReq>(Arena*);
template<> ::cloudnic::CompressImgResp* Arena::CreateMaybeMessage<::cloudnic::CompressImgResp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cloudnic {

// ===================================================================

class CompressImgReq final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:cloudnic.CompressImgReq) */ {
 public:
  inline CompressImgReq() : CompressImgReq(nullptr) {}
  ~CompressImgReq() override;
  explicit PROTOBUF_CONSTEXPR CompressImgReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompressImgReq(const CompressImgReq& from);
  CompressImgReq(CompressImgReq&& from) noexcept
    : CompressImgReq() {
    *this = ::std::move(from);
  }

  inline CompressImgReq& operator=(const CompressImgReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompressImgReq& operator=(CompressImgReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const CompressImgReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompressImgReq* internal_default_instance() {
    return reinterpret_cast<const CompressImgReq*>(
               &_CompressImgReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CompressImgReq& a, CompressImgReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CompressImgReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompressImgReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompressImgReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompressImgReq>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const CompressImgReq& from);
  void MergeFrom(const CompressImgReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CompressImgReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudnic.CompressImgReq";
  }
  protected:
  explicit CompressImgReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImgFieldNumber = 2,
    kImgIdFieldNumber = 1,
  };
  // optional string img = 2;
  bool has_img() const;
  private:
  bool _internal_has_img() const;
  public:
  void clear_img();
  const std::string& img() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_img(ArgT0&& arg0, ArgT... args);
  std::string* mutable_img();
  PROTOBUF_NODISCARD std::string* release_img();
  void set_allocated_img(std::string* img);
  private:
  const std::string& _internal_img() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_img(const std::string& value);
  std::string* _internal_mutable_img();
  public:

  // optional int64 img_id = 1;
  bool has_img_id() const;
  private:
  bool _internal_has_img_id() const;
  public:
  void clear_img_id();
  int64_t img_id() const;
  void set_img_id(int64_t value);
  private:
  int64_t _internal_img_id() const;
  void _internal_set_img_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:cloudnic.CompressImgReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr img_;
  int64_t img_id_;
  friend struct ::TableStruct_cloudnic_2eproto;
};
// -------------------------------------------------------------------

class CompressImgResp final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:cloudnic.CompressImgResp) */ {
 public:
  inline CompressImgResp() : CompressImgResp(nullptr) {}
  ~CompressImgResp() override;
  explicit PROTOBUF_CONSTEXPR CompressImgResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompressImgResp(const CompressImgResp& from);
  CompressImgResp(CompressImgResp&& from) noexcept
    : CompressImgResp() {
    *this = ::std::move(from);
  }

  inline CompressImgResp& operator=(const CompressImgResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompressImgResp& operator=(CompressImgResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const CompressImgResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompressImgResp* internal_default_instance() {
    return reinterpret_cast<const CompressImgResp*>(
               &_CompressImgResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CompressImgResp& a, CompressImgResp& b) {
    a.Swap(&b);
  }
  inline void Swap(CompressImgResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompressImgResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompressImgResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompressImgResp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const CompressImgResp& from);
  void MergeFrom(const CompressImgResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CompressImgResp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudnic.CompressImgResp";
  }
  protected:
  explicit CompressImgResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImgFieldNumber = 2,
    kImgIdFieldNumber = 1,
  };
  // optional string img = 2;
  bool has_img() const;
  private:
  bool _internal_has_img() const;
  public:
  void clear_img();
  const std::string& img() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_img(ArgT0&& arg0, ArgT... args);
  std::string* mutable_img();
  PROTOBUF_NODISCARD std::string* release_img();
  void set_allocated_img(std::string* img);
  private:
  const std::string& _internal_img() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_img(const std::string& value);
  std::string* _internal_mutable_img();
  public:

  // optional int64 img_id = 1;
  bool has_img_id() const;
  private:
  bool _internal_has_img_id() const;
  public:
  void clear_img_id();
  int64_t img_id() const;
  void set_img_id(int64_t value);
  private:
  int64_t _internal_img_id() const;
  void _internal_set_img_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:cloudnic.CompressImgResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr img_;
  int64_t img_id_;
  friend struct ::TableStruct_cloudnic_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CompressImgReq

// optional int64 img_id = 1;
inline bool CompressImgReq::_internal_has_img_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CompressImgReq::has_img_id() const {
  return _internal_has_img_id();
}
inline void CompressImgReq::clear_img_id() {
  img_id_ = int64_t{0};
  _has_bits_[0] &= ~0x00000002u;
}
inline int64_t CompressImgReq::_internal_img_id() const {
  return img_id_;
}
inline int64_t CompressImgReq::img_id() const {
  // @@protoc_insertion_point(field_get:cloudnic.CompressImgReq.img_id)
  return _internal_img_id();
}
inline void CompressImgReq::_internal_set_img_id(int64_t value) {
  _has_bits_[0] |= 0x00000002u;
  img_id_ = value;
}
inline void CompressImgReq::set_img_id(int64_t value) {
  _internal_set_img_id(value);
  // @@protoc_insertion_point(field_set:cloudnic.CompressImgReq.img_id)
}

// optional string img = 2;
inline bool CompressImgReq::_internal_has_img() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CompressImgReq::has_img() const {
  return _internal_has_img();
}
inline void CompressImgReq::clear_img() {
  img_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CompressImgReq::img() const {
  // @@protoc_insertion_point(field_get:cloudnic.CompressImgReq.img)
  return _internal_img();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompressImgReq::set_img(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 img_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cloudnic.CompressImgReq.img)
}
inline std::string* CompressImgReq::mutable_img() {
  std::string* _s = _internal_mutable_img();
  // @@protoc_insertion_point(field_mutable:cloudnic.CompressImgReq.img)
  return _s;
}
inline const std::string& CompressImgReq::_internal_img() const {
  return img_.Get();
}
inline void CompressImgReq::_internal_set_img(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  img_.Set(value, GetArenaForAllocation());
}
inline std::string* CompressImgReq::_internal_mutable_img() {
  _has_bits_[0] |= 0x00000001u;
  return img_.Mutable(GetArenaForAllocation());
}
inline std::string* CompressImgReq::release_img() {
  // @@protoc_insertion_point(field_release:cloudnic.CompressImgReq.img)
  if (!_internal_has_img()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = img_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (img_.IsDefault()) {
    img_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void CompressImgReq::set_allocated_img(std::string* img) {
  if (img != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  img_.SetAllocated(img, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (img_.IsDefault()) {
    img_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cloudnic.CompressImgReq.img)
}

// -------------------------------------------------------------------

// CompressImgResp

// optional int64 img_id = 1;
inline bool CompressImgResp::_internal_has_img_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CompressImgResp::has_img_id() const {
  return _internal_has_img_id();
}
inline void CompressImgResp::clear_img_id() {
  img_id_ = int64_t{0};
  _has_bits_[0] &= ~0x00000002u;
}
inline int64_t CompressImgResp::_internal_img_id() const {
  return img_id_;
}
inline int64_t CompressImgResp::img_id() const {
  // @@protoc_insertion_point(field_get:cloudnic.CompressImgResp.img_id)
  return _internal_img_id();
}
inline void CompressImgResp::_internal_set_img_id(int64_t value) {
  _has_bits_[0] |= 0x00000002u;
  img_id_ = value;
}
inline void CompressImgResp::set_img_id(int64_t value) {
  _internal_set_img_id(value);
  // @@protoc_insertion_point(field_set:cloudnic.CompressImgResp.img_id)
}

// optional string img = 2;
inline bool CompressImgResp::_internal_has_img() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CompressImgResp::has_img() const {
  return _internal_has_img();
}
inline void CompressImgResp::clear_img() {
  img_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CompressImgResp::img() const {
  // @@protoc_insertion_point(field_get:cloudnic.CompressImgResp.img)
  return _internal_img();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompressImgResp::set_img(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 img_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cloudnic.CompressImgResp.img)
}
inline std::string* CompressImgResp::mutable_img() {
  std::string* _s = _internal_mutable_img();
  // @@protoc_insertion_point(field_mutable:cloudnic.CompressImgResp.img)
  return _s;
}
inline const std::string& CompressImgResp::_internal_img() const {
  return img_.Get();
}
inline void CompressImgResp::_internal_set_img(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  img_.Set(value, GetArenaForAllocation());
}
inline std::string* CompressImgResp::_internal_mutable_img() {
  _has_bits_[0] |= 0x00000001u;
  return img_.Mutable(GetArenaForAllocation());
}
inline std::string* CompressImgResp::release_img() {
  // @@protoc_insertion_point(field_release:cloudnic.CompressImgResp.img)
  if (!_internal_has_img()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = img_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (img_.IsDefault()) {
    img_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void CompressImgResp::set_allocated_img(std::string* img) {
  if (img != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  img_.SetAllocated(img, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (img_.IsDefault()) {
    img_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cloudnic.CompressImgResp.img)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cloudnic

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cloudnic_2eproto
